### PR TITLE
fix build config

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by leo60228** [comment]
Have you tried re-enabling magick-plus-plus?

**Comment by staticfloat** [comment]
Yeah, I can confirm that removing the `LDFLAGS` stuff fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/372

**Comment by leo60228** [comment]
@SimonDanisch already tried that, it didn't work D:

**Comment by SimonDanisch** [comment]
[edit: this was meant for https://github.com/JuliaIO/ImageMagick.jl/pull/141, but I guess makes sense here as well]

This PR just needs to fix:
```
/opt/x86_64-apple-darwin14/bin/x86_64-apple-darwin14-ranlib: archive member: /workspace/destdir/lib/libMagick++-6.Q16.a(
�Y) size too large (archive member extends past the end of the file)
make[2]: *** [Makefile:5466: install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/workspace/srcdir/ImageMagick6'
make[1]: *** [Makefile:11355: install-am] Error 2
make[1]: Leaving directory '/workspace/srcdir/ImageMagick6'
make: *** [Makefile:11349: install] Error 2
ERROR: LoadError: Build for ImageMagick on x86_64-apple-darwin14 did not complete successfully
```
I googled it a bit but couldn't really find something that made sense to me - then again, I'm even less familiar with OSX build tools than I'm already with linux build tools :D

**Comment by Vexatos** [comment]
Any news on this?

**Comment by giordano** [comment]
This has been superseded by #9 and can be closed

**Pull request closed without merging**
